// Code generated by protoc-gen-go. DO NOT EDIT.
// source: microservices-example-go/product/internal/proto-files/service/product-service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	domain "microservices-example-go/product/internal/grpc/domain"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProductResponse struct {
	Product              *domain.Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d7aa9ec1d87a608, []int{0}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *domain.Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProductResponse)(nil), "service.GetProductResponse")
}

func init() {
	proto.RegisterFile("microservices-example-go/product/internal/proto-files/service/product-service.proto", fileDescriptor_1d7aa9ec1d87a608)
}

var fileDescriptor_1d7aa9ec1d87a608 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x0a, 0xce, 0xcd, 0x4c, 0x2e,
	0xca, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x4d, 0xad, 0x48, 0xcc, 0x2d, 0xc8,
	0x49, 0xd5, 0x4d, 0xcf, 0xd7, 0x2f, 0x28, 0xca, 0x4f, 0x29, 0x4d, 0x2e, 0xd1, 0xcf, 0xcc, 0x2b,
	0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x01, 0x09, 0x94, 0xe4, 0xeb, 0xa6, 0x65, 0xe6, 0xa4, 0x16, 0xeb,
	0x43, 0x35, 0xc0, 0x14, 0xe9, 0x42, 0xf9, 0x7a, 0x60, 0x35, 0x42, 0xec, 0x50, 0xae, 0x94, 0x17,
	0x79, 0xa6, 0xa7, 0xe4, 0xe7, 0x26, 0x66, 0xe6, 0xc1, 0xd4, 0x40, 0x0c, 0x55, 0xb2, 0xe7, 0x12,
	0x72, 0x4f, 0x2d, 0x09, 0x80, 0x88, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x69,
	0x72, 0xb1, 0x43, 0x95, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xeb, 0x41, 0x74, 0xeb,
	0x41, 0x85, 0x83, 0x60, 0xf2, 0x46, 0xae, 0x5c, 0x7c, 0x50, 0xdd, 0xc1, 0x10, 0x07, 0x09, 0x19,
	0x73, 0x31, 0xa7, 0xa7, 0x96, 0x08, 0xa1, 0x6b, 0x91, 0x92, 0xd6, 0x83, 0xf9, 0x07, 0xd3, 0x46,
	0x27, 0x8b, 0x28, 0x33, 0xe2, 0x7d, 0x95, 0x5e, 0x54, 0x90, 0x0c, 0x0b, 0xac, 0x24, 0x36, 0xb0,
	0x47, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xdd, 0x67, 0x0b, 0x74, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Get(ctx context.Context, in *domain.Product, opts ...grpc.CallOption) (*GetProductResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Get(ctx context.Context, in *domain.Product, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/service.ProductService/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Get(context.Context, *domain.Product) (*GetProductResponse, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) Get(ctx context.Context, req *domain.Product) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(domain.Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ProductService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Get(ctx, req.(*domain.Product))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _ProductService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microservices-example-go/product/internal/proto-files/service/product-service.proto",
}
